# Generated by Django 5.0 on 2023-12-19 03:02

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DisputeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=50, unique=True, verbose_name='Выбор')),
            ],
            options={
                'verbose_name': 'Решение по рекламации',
                'verbose_name_plural': 'Решения по рекламациям',
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товаров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now=True, verbose_name='Время начала')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Корзина покупок',
                'verbose_name_plural': 'Корзины покупок',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('items', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Состав заказа')),
                ('payment_date', models.DateTimeField(verbose_name='Дата оплаты')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость заказа')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'История заказов',
                'verbose_name_plural': 'Истории заказов',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dispute_text', models.TextField(verbose_name='Суть претензии')),
                ('decision_text', models.TextField(blank=True, null=True, verbose_name='Суть решения')),
                ('decision_date', models.DateTimeField(null=True, verbose_name='Дата принятого решения')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='shop.disputechoice', verbose_name='Принятое решение')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='shop.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('in_sale', models.BooleanField(default=False, verbose_name='В продаже')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CartContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.cart', verbose_name='Состав корзины')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.product')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.productproperty', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товара',
                'ordering': ['property__name'],
                'unique_together': {('product', 'property')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.ManyToManyField(through='shop.PropertyValue', to='shop.productproperty', verbose_name='Характеристики'),
        ),
    ]
