# Generated by Django 5.0 on 2023-12-19 12:07

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.image_file_path_generator, verbose_name='Изображение'),
        ),
    ]
